### ISSUE TITLE
augur.js doesn't work on Node 6.1.0

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur.js#95]
Looks like a problem with the node-localStorage module:
```
TypeError: Proxy.create is not a function
    at new LocalStorage (/Users/k_day/src/augur/augur.js/node_modules/node-localstorage/LocalStorage.js:143:45)
    at Object.<anonymous> (/Users/k_day/src/augur/augur.js/src/client/db.js:13:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at new Augur (/Users/k_day/src/augur/augur.js/src/index.js:45:15)
```

**Comment by tinybike** [comment]
Magically fixed itself when we stopped using node-localStorage.
